/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.cooper.jooq.model.Keys;
import org.cooper.jooq.model.Public;
import org.cooper.jooq.model.tables.CloudletMetric.CloudletMetricPath;
import org.cooper.jooq.model.tables.Simulation.SimulationPath;
import org.cooper.jooq.model.tables.Vm.VmPath;
import org.cooper.jooq.model.tables.records.CloudletRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cloudlet extends TableImpl<CloudletRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cloudlet</code>
     */
    public static final Cloudlet CLOUDLET = new Cloudlet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CloudletRecord> getRecordType() {
        return CloudletRecord.class;
    }

    /**
     * The column <code>public.cloudlet.id</code>.
     */
    public final TableField<CloudletRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.cloudlet.simulation_id</code>.
     */
    public final TableField<CloudletRecord, UUID> SIMULATION_ID = createField(DSL.name("simulation_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.cloudlet.vm_id</code>.
     */
    public final TableField<CloudletRecord, UUID> VM_ID = createField(DSL.name("vm_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.cloudlet.cloudsim_id</code>.
     */
    public final TableField<CloudletRecord, Long> CLOUDSIM_ID = createField(DSL.name("cloudsim_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.cloudlet.length</code>.
     */
    public final TableField<CloudletRecord, Long> LENGTH = createField(DSL.name("length"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.cloudlet.start_time_seconds</code>.
     */
    public final TableField<CloudletRecord, Double> START_TIME_SECONDS = createField(DSL.name("start_time_seconds"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.cloudlet.finish_time_seconds</code>.
     */
    public final TableField<CloudletRecord, Double> FINISH_TIME_SECONDS = createField(DSL.name("finish_time_seconds"), SQLDataType.DOUBLE, this, "");

    private Cloudlet(Name alias, Table<CloudletRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cloudlet(Name alias, Table<CloudletRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.cloudlet</code> table reference
     */
    public Cloudlet(String alias) {
        this(DSL.name(alias), CLOUDLET);
    }

    /**
     * Create an aliased <code>public.cloudlet</code> table reference
     */
    public Cloudlet(Name alias) {
        this(alias, CLOUDLET);
    }

    /**
     * Create a <code>public.cloudlet</code> table reference
     */
    public Cloudlet() {
        this(DSL.name("cloudlet"), null);
    }

    public <O extends Record> Cloudlet(Table<O> path, ForeignKey<O, CloudletRecord> childPath, InverseForeignKey<O, CloudletRecord> parentPath) {
        super(path, childPath, parentPath, CLOUDLET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CloudletPath extends Cloudlet implements Path<CloudletRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CloudletPath(Table<O> path, ForeignKey<O, CloudletRecord> childPath, InverseForeignKey<O, CloudletRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CloudletPath(Name alias, Table<CloudletRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CloudletPath as(String alias) {
            return new CloudletPath(DSL.name(alias), this);
        }

        @Override
        public CloudletPath as(Name alias) {
            return new CloudletPath(alias, this);
        }

        @Override
        public CloudletPath as(Table<?> alias) {
            return new CloudletPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CloudletRecord> getPrimaryKey() {
        return Keys.CLOUDLET_PKEY;
    }

    @Override
    public List<ForeignKey<CloudletRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLOUDLET__CLOUDLET_SIMULATION_ID_FKEY, Keys.CLOUDLET__CLOUDLET_VM_ID_FKEY);
    }

    private transient SimulationPath _simulation;

    /**
     * Get the implicit join path to the <code>public.simulation</code> table.
     */
    public SimulationPath simulation() {
        if (_simulation == null)
            _simulation = new SimulationPath(this, Keys.CLOUDLET__CLOUDLET_SIMULATION_ID_FKEY, null);

        return _simulation;
    }

    private transient VmPath _vm;

    /**
     * Get the implicit join path to the <code>public.vm</code> table.
     */
    public VmPath vm() {
        if (_vm == null)
            _vm = new VmPath(this, Keys.CLOUDLET__CLOUDLET_VM_ID_FKEY, null);

        return _vm;
    }

    private transient CloudletMetricPath _cloudletMetric;

    /**
     * Get the implicit to-many join path to the
     * <code>public.cloudlet_metric</code> table
     */
    public CloudletMetricPath cloudletMetric() {
        if (_cloudletMetric == null)
            _cloudletMetric = new CloudletMetricPath(this, null, Keys.CLOUDLET_METRIC__CLOUDLET_METRIC_CLOUDLET_ID_FKEY.getInverseKey());

        return _cloudletMetric;
    }

    @Override
    public Cloudlet as(String alias) {
        return new Cloudlet(DSL.name(alias), this);
    }

    @Override
    public Cloudlet as(Name alias) {
        return new Cloudlet(alias, this);
    }

    @Override
    public Cloudlet as(Table<?> alias) {
        return new Cloudlet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cloudlet rename(String name) {
        return new Cloudlet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cloudlet rename(Name name) {
        return new Cloudlet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cloudlet rename(Table<?> name) {
        return new Cloudlet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet where(Condition condition) {
        return new Cloudlet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cloudlet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cloudlet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cloudlet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cloudlet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cloudlet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
