/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.cooper.jooq.model.Keys;
import org.cooper.jooq.model.Public;
import org.cooper.jooq.model.tables.HostMetric.HostMetricPath;
import org.cooper.jooq.model.tables.Simulation.SimulationPath;
import org.cooper.jooq.model.tables.Vm.VmPath;
import org.cooper.jooq.model.tables.records.HostRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Host extends TableImpl<HostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.host</code>
     */
    public static final Host HOST = new Host();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostRecord> getRecordType() {
        return HostRecord.class;
    }

    /**
     * The column <code>public.host.id</code>.
     */
    public final TableField<HostRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.host.simulation_id</code>.
     */
    public final TableField<HostRecord, UUID> SIMULATION_ID = createField(DSL.name("simulation_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.host.cloudsim_id</code>.
     */
    public final TableField<HostRecord, Long> CLOUDSIM_ID = createField(DSL.name("cloudsim_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.host.start_time_seconds</code>.
     */
    public final TableField<HostRecord, Double> START_TIME_SECONDS = createField(DSL.name("start_time_seconds"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.host.finish_time_seconds</code>.
     */
    public final TableField<HostRecord, Double> FINISH_TIME_SECONDS = createField(DSL.name("finish_time_seconds"), SQLDataType.DOUBLE, this, "");

    private Host(Name alias, Table<HostRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Host(Name alias, Table<HostRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.host</code> table reference
     */
    public Host(String alias) {
        this(DSL.name(alias), HOST);
    }

    /**
     * Create an aliased <code>public.host</code> table reference
     */
    public Host(Name alias) {
        this(alias, HOST);
    }

    /**
     * Create a <code>public.host</code> table reference
     */
    public Host() {
        this(DSL.name("host"), null);
    }

    public <O extends Record> Host(Table<O> path, ForeignKey<O, HostRecord> childPath, InverseForeignKey<O, HostRecord> parentPath) {
        super(path, childPath, parentPath, HOST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HostPath extends Host implements Path<HostRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HostPath(Table<O> path, ForeignKey<O, HostRecord> childPath, InverseForeignKey<O, HostRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HostPath(Name alias, Table<HostRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HostPath as(String alias) {
            return new HostPath(DSL.name(alias), this);
        }

        @Override
        public HostPath as(Name alias) {
            return new HostPath(alias, this);
        }

        @Override
        public HostPath as(Table<?> alias) {
            return new HostPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<HostRecord> getPrimaryKey() {
        return Keys.HOST_PKEY;
    }

    @Override
    public List<ForeignKey<HostRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HOST__HOST_SIMULATION_ID_FKEY);
    }

    private transient SimulationPath _simulation;

    /**
     * Get the implicit join path to the <code>public.simulation</code> table.
     */
    public SimulationPath simulation() {
        if (_simulation == null)
            _simulation = new SimulationPath(this, Keys.HOST__HOST_SIMULATION_ID_FKEY, null);

        return _simulation;
    }

    private transient HostMetricPath _hostMetric;

    /**
     * Get the implicit to-many join path to the <code>public.host_metric</code>
     * table
     */
    public HostMetricPath hostMetric() {
        if (_hostMetric == null)
            _hostMetric = new HostMetricPath(this, null, Keys.HOST_METRIC__HOST_METRIC_HOST_ID_FKEY.getInverseKey());

        return _hostMetric;
    }

    private transient VmPath _vm;

    /**
     * Get the implicit to-many join path to the <code>public.vm</code> table
     */
    public VmPath vm() {
        if (_vm == null)
            _vm = new VmPath(this, null, Keys.VM__VM_HOST_ID_FKEY.getInverseKey());

        return _vm;
    }

    @Override
    public Host as(String alias) {
        return new Host(DSL.name(alias), this);
    }

    @Override
    public Host as(Name alias) {
        return new Host(alias, this);
    }

    @Override
    public Host as(Table<?> alias) {
        return new Host(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Host rename(String name) {
        return new Host(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Host rename(Name name) {
        return new Host(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Host rename(Table<?> name) {
        return new Host(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host where(Condition condition) {
        return new Host(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Host where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Host where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Host where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Host where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Host whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
