/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables;


import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.cooper.jooq.model.Keys;
import org.cooper.jooq.model.Public;
import org.cooper.jooq.model.tables.Cloudlet.CloudletPath;
import org.cooper.jooq.model.tables.Host.HostPath;
import org.cooper.jooq.model.tables.Time.TimePath;
import org.cooper.jooq.model.tables.Vm.VmPath;
import org.cooper.jooq.model.tables.records.SimulationRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Simulation extends TableImpl<SimulationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.simulation</code>
     */
    public static final Simulation SIMULATION = new Simulation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimulationRecord> getRecordType() {
        return SimulationRecord.class;
    }

    /**
     * The column <code>public.simulation.id</code>.
     */
    public final TableField<SimulationRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.simulation.name</code>.
     */
    public final TableField<SimulationRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.simulation.started_at</code>.
     */
    public final TableField<SimulationRecord, LocalDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.simulation.ended_at</code>.
     */
    public final TableField<SimulationRecord, LocalDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Simulation(Name alias, Table<SimulationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Simulation(Name alias, Table<SimulationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.simulation</code> table reference
     */
    public Simulation(String alias) {
        this(DSL.name(alias), SIMULATION);
    }

    /**
     * Create an aliased <code>public.simulation</code> table reference
     */
    public Simulation(Name alias) {
        this(alias, SIMULATION);
    }

    /**
     * Create a <code>public.simulation</code> table reference
     */
    public Simulation() {
        this(DSL.name("simulation"), null);
    }

    public <O extends Record> Simulation(Table<O> path, ForeignKey<O, SimulationRecord> childPath, InverseForeignKey<O, SimulationRecord> parentPath) {
        super(path, childPath, parentPath, SIMULATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SimulationPath extends Simulation implements Path<SimulationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SimulationPath(Table<O> path, ForeignKey<O, SimulationRecord> childPath, InverseForeignKey<O, SimulationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SimulationPath(Name alias, Table<SimulationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SimulationPath as(String alias) {
            return new SimulationPath(DSL.name(alias), this);
        }

        @Override
        public SimulationPath as(Name alias) {
            return new SimulationPath(alias, this);
        }

        @Override
        public SimulationPath as(Table<?> alias) {
            return new SimulationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SimulationRecord> getPrimaryKey() {
        return Keys.SIMULATION_PKEY;
    }

    private transient CloudletPath _cloudlet;

    /**
     * Get the implicit to-many join path to the <code>public.cloudlet</code>
     * table
     */
    public CloudletPath cloudlet() {
        if (_cloudlet == null)
            _cloudlet = new CloudletPath(this, null, Keys.CLOUDLET__CLOUDLET_SIMULATION_ID_FKEY.getInverseKey());

        return _cloudlet;
    }

    private transient HostPath _host;

    /**
     * Get the implicit to-many join path to the <code>public.host</code> table
     */
    public HostPath host() {
        if (_host == null)
            _host = new HostPath(this, null, Keys.HOST__HOST_SIMULATION_ID_FKEY.getInverseKey());

        return _host;
    }

    private transient TimePath _time;

    /**
     * Get the implicit to-many join path to the <code>public.time</code> table
     */
    public TimePath time() {
        if (_time == null)
            _time = new TimePath(this, null, Keys.TIME__TIME_SIMULATION_ID_FKEY.getInverseKey());

        return _time;
    }

    private transient VmPath _vm;

    /**
     * Get the implicit to-many join path to the <code>public.vm</code> table
     */
    public VmPath vm() {
        if (_vm == null)
            _vm = new VmPath(this, null, Keys.VM__VM_SIMULATION_ID_FKEY.getInverseKey());

        return _vm;
    }

    @Override
    public Simulation as(String alias) {
        return new Simulation(DSL.name(alias), this);
    }

    @Override
    public Simulation as(Name alias) {
        return new Simulation(alias, this);
    }

    @Override
    public Simulation as(Table<?> alias) {
        return new Simulation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Simulation rename(String name) {
        return new Simulation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Simulation rename(Name name) {
        return new Simulation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Simulation rename(Table<?> name) {
        return new Simulation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation where(Condition condition) {
        return new Simulation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Simulation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Simulation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Simulation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Simulation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Simulation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
