/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.cooper.jooq.model.Keys;
import org.cooper.jooq.model.Public;
import org.cooper.jooq.model.tables.Vm.VmPath;
import org.cooper.jooq.model.tables.records.VmMetricRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VmMetric extends TableImpl<VmMetricRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vm_metric</code>
     */
    public static final VmMetric VM_METRIC = new VmMetric();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VmMetricRecord> getRecordType() {
        return VmMetricRecord.class;
    }

    /**
     * The column <code>public.vm_metric.id</code>.
     */
    public final TableField<VmMetricRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.vm_metric.vm_id</code>.
     */
    public final TableField<VmMetricRecord, UUID> VM_ID = createField(DSL.name("vm_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.vm_metric.simulation_time_seconds</code>.
     */
    public final TableField<VmMetricRecord, Double> SIMULATION_TIME_SECONDS = createField(DSL.name("simulation_time_seconds"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vm_metric.ram_allocated_mb</code>.
     */
    public final TableField<VmMetricRecord, Long> RAM_ALLOCATED_MB = createField(DSL.name("ram_allocated_mb"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vm_metric.ram_available_mb</code>.
     */
    public final TableField<VmMetricRecord, Long> RAM_AVAILABLE_MB = createField(DSL.name("ram_available_mb"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vm_metric.cpu_utilization</code>.
     */
    public final TableField<VmMetricRecord, Double> CPU_UTILIZATION = createField(DSL.name("cpu_utilization"), SQLDataType.DOUBLE.nullable(false), this, "");

    private VmMetric(Name alias, Table<VmMetricRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VmMetric(Name alias, Table<VmMetricRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vm_metric</code> table reference
     */
    public VmMetric(String alias) {
        this(DSL.name(alias), VM_METRIC);
    }

    /**
     * Create an aliased <code>public.vm_metric</code> table reference
     */
    public VmMetric(Name alias) {
        this(alias, VM_METRIC);
    }

    /**
     * Create a <code>public.vm_metric</code> table reference
     */
    public VmMetric() {
        this(DSL.name("vm_metric"), null);
    }

    public <O extends Record> VmMetric(Table<O> path, ForeignKey<O, VmMetricRecord> childPath, InverseForeignKey<O, VmMetricRecord> parentPath) {
        super(path, childPath, parentPath, VM_METRIC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VmMetricPath extends VmMetric implements Path<VmMetricRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VmMetricPath(Table<O> path, ForeignKey<O, VmMetricRecord> childPath, InverseForeignKey<O, VmMetricRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VmMetricPath(Name alias, Table<VmMetricRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VmMetricPath as(String alias) {
            return new VmMetricPath(DSL.name(alias), this);
        }

        @Override
        public VmMetricPath as(Name alias) {
            return new VmMetricPath(alias, this);
        }

        @Override
        public VmMetricPath as(Table<?> alias) {
            return new VmMetricPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<VmMetricRecord> getPrimaryKey() {
        return Keys.VM_METRIC_PKEY;
    }

    @Override
    public List<ForeignKey<VmMetricRecord, ?>> getReferences() {
        return Arrays.asList(Keys.VM_METRIC__VM_METRIC_VM_ID_FKEY);
    }

    private transient VmPath _vm;

    /**
     * Get the implicit join path to the <code>public.vm</code> table.
     */
    public VmPath vm() {
        if (_vm == null)
            _vm = new VmPath(this, Keys.VM_METRIC__VM_METRIC_VM_ID_FKEY, null);

        return _vm;
    }

    @Override
    public VmMetric as(String alias) {
        return new VmMetric(DSL.name(alias), this);
    }

    @Override
    public VmMetric as(Name alias) {
        return new VmMetric(alias, this);
    }

    @Override
    public VmMetric as(Table<?> alias) {
        return new VmMetric(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VmMetric rename(String name) {
        return new VmMetric(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VmMetric rename(Name name) {
        return new VmMetric(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VmMetric rename(Table<?> name) {
        return new VmMetric(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric where(Condition condition) {
        return new VmMetric(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VmMetric where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VmMetric where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VmMetric where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VmMetric where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VmMetric whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
