/*
 * This file is generated by jOOQ.
 */
package org.cloudvisualization.jooq.model;


import org.cloudvisualization.jooq.model.tables.FlywaySchemaHistory;
import org.cloudvisualization.jooq.model.tables.Simulation;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.simulation</code>.
     */
    public static final Simulation SIMULATION = Simulation.SIMULATION;
}
