/*
 * This file is generated by jOOQ.
 */
package org.cloudvisualization.jooq.model.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.cloudvisualization.jooq.model.tables.Simulation;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SimulationRecord extends UpdatableRecordImpl<SimulationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.simulation.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.simulation.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.simulation.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.simulation.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.simulation.started_at</code>.
     */
    public void setStartedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.simulation.started_at</code>.
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.simulation.ended_at</code>.
     */
    public void setEndedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.simulation.ended_at</code>.
     */
    public LocalDateTime getEndedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimulationRecord
     */
    public SimulationRecord() {
        super(Simulation.SIMULATION);
    }

    /**
     * Create a detached, initialised SimulationRecord
     */
    public SimulationRecord(UUID id, String name, LocalDateTime startedAt, LocalDateTime endedAt) {
        super(Simulation.SIMULATION);

        setId(id);
        setName(name);
        setStartedAt(startedAt);
        setEndedAt(endedAt);
        resetChangedOnNotNull();
    }
}
