/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables.records;


import java.util.UUID;

import org.cooper.jooq.model.tables.Cloudlet;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CloudletRecord extends UpdatableRecordImpl<CloudletRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cloudlet.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cloudlet.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.cloudlet.simulation_id</code>.
     */
    public void setSimulationId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cloudlet.simulation_id</code>.
     */
    public UUID getSimulationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.cloudlet.vm_id</code>.
     */
    public void setVmId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cloudlet.vm_id</code>.
     */
    public UUID getVmId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.cloudlet.cloudsim_id</code>.
     */
    public void setCloudsimId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cloudlet.cloudsim_id</code>.
     */
    public Long getCloudsimId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.cloudlet.length</code>.
     */
    public void setLength(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cloudlet.length</code>.
     */
    public Long getLength() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.cloudlet.start_time_seconds</code>.
     */
    public void setStartTimeSeconds(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cloudlet.start_time_seconds</code>.
     */
    public Double getStartTimeSeconds() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.cloudlet.finish_time_seconds</code>.
     */
    public void setFinishTimeSeconds(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cloudlet.finish_time_seconds</code>.
     */
    public Double getFinishTimeSeconds() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CloudletRecord
     */
    public CloudletRecord() {
        super(Cloudlet.CLOUDLET);
    }

    /**
     * Create a detached, initialised CloudletRecord
     */
    public CloudletRecord(UUID id, UUID simulationId, UUID vmId, Long cloudsimId, Long length, Double startTimeSeconds, Double finishTimeSeconds) {
        super(Cloudlet.CLOUDLET);

        setId(id);
        setSimulationId(simulationId);
        setVmId(vmId);
        setCloudsimId(cloudsimId);
        setLength(length);
        setStartTimeSeconds(startTimeSeconds);
        setFinishTimeSeconds(finishTimeSeconds);
        resetChangedOnNotNull();
    }
}
