/*
 * This file is generated by jOOQ.
 */
package org.cooper.jooq.model.tables.records;


import java.util.UUID;

import org.cooper.jooq.model.tables.Vm;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VmRecord extends UpdatableRecordImpl<VmRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vm.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vm.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.vm.simulation_id</code>.
     */
    public void setSimulationId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vm.simulation_id</code>.
     */
    public UUID getSimulationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.vm.host_id</code>.
     */
    public void setHostId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vm.host_id</code>.
     */
    public UUID getHostId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.vm.cloudsim_id</code>.
     */
    public void setCloudsimId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vm.cloudsim_id</code>.
     */
    public Long getCloudsimId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.vm.start_time_seconds</code>.
     */
    public void setStartTimeSeconds(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vm.start_time_seconds</code>.
     */
    public Double getStartTimeSeconds() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.vm.finish_time_seconds</code>.
     */
    public void setFinishTimeSeconds(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vm.finish_time_seconds</code>.
     */
    public Double getFinishTimeSeconds() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VmRecord
     */
    public VmRecord() {
        super(Vm.VM);
    }

    /**
     * Create a detached, initialised VmRecord
     */
    public VmRecord(UUID id, UUID simulationId, UUID hostId, Long cloudsimId, Double startTimeSeconds, Double finishTimeSeconds) {
        super(Vm.VM);

        setId(id);
        setSimulationId(simulationId);
        setHostId(hostId);
        setCloudsimId(cloudsimId);
        setStartTimeSeconds(startTimeSeconds);
        setFinishTimeSeconds(finishTimeSeconds);
        resetChangedOnNotNull();
    }
}
